//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AperturaCaja
    {
        public int AperturaCajaId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<decimal> ImporteInicial { get; set; }
        public Nullable<decimal> ImporteCierre { get; set; }
        public Nullable<int> UsuarioAperturaId { get; set; }
        public Nullable<int> UsuarioCierreId { get; set; }
    }
}
