//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleActividadMantenimiento
    {
        public int IdDetalleActividadMantenimiento { get; set; }
        public Nullable<int> IdMantenimiento { get; set; }
        public Nullable<int> IdActividadMantenimiento { get; set; }
    
        public virtual ActividadMantenimiento ActividadMantenimiento { get; set; }
        public virtual Mantenimiento Mantenimiento { get; set; }
    }
}
