//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoVehiculos
    {
        public int IDMantenimiento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Km { get; set; }
        public string Detalle { get; set; }
        public string NombreTaller { get; set; }
        public string Direccion { get; set; }
        public string Patente { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
    }
}
