//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mantenimiento()
        {
            this.DetalleActividadMantenimiento = new HashSet<DetalleActividadMantenimiento>();
            this.DetalleMantenimientoRepuestos = new HashSet<DetalleMantenimientoRepuestos>();
        }
    
        public int IDMantenimiento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<int> Km { get; set; }
        public Nullable<int> IDTaller { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> IDUserTransac { get; set; }
        public Nullable<double> Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleActividadMantenimiento> DetalleActividadMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMantenimientoRepuestos> DetalleMantenimientoRepuestos { get; set; }
        public virtual Talleres Talleres { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
