//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PadronRgsRet
    {
        public int ID { get; set; }
        public string Regimen { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public string Cuit { get; set; }
        public string TipoContribuyenteInsc { get; set; }
        public string MarcaAltaBaja { get; set; }
        public string MarcaCambioAlicuota { get; set; }
        public double Alicuota { get; set; }
        public int Grupo { get; set; }
    }
}
