//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCuentas
    {
        public int codigo { get; set; }
        public Nullable<int> parentID { get; set; }
        public string descriptionCuenta { get; set; }
        public Nullable<int> depth { get; set; }
        public Nullable<int> pathIndex { get; set; }
        public string numericalmapping { get; set; }
        public string operacion { get; set; }
        public Nullable<int> partidadobleID { get; set; }
    
        public virtual PartidaDoble PartidaDoble { get; set; }
    }
}
