//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retenciones
    {
        public int IDRetencion { get; set; }
        public string RetencionCode { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Alicuota { get; set; }
        public Nullable<double> Importe { get; set; }
        public Nullable<int> EmpresaID { get; set; }
        public int IdPago { get; set; }
    
        public virtual Pagos Pagos { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
